### PR TITLE
Capitalized table name tests

### PR DESCRIPTION
**Pull request by cindyatnycdot**
I wrote 2 tests with capitalized names (in case a user includes a capital). The MS test passes but not the PG test `test_backup_tables_capitalized`.

### CODE REVIEW

**Comment by shostetter** [comment]
Which branch did you branch off of for this, i dont see your code in the diff

**Comment by cindyatnycdot** [comment]
It was from `73-table-backup`. I've fixed the rebase now (sorry the commit history looks so messy). I had thought that `76-not-case-sensitive` was built on top of `73-table-backup` so that the backup table functions + the case sensitive check happened in the same branch, but now i realize they're not. i will retry my `pytests`

**Comment by shostetter** [comment]
> It was from `73-table-backup`. I've fixed the rebase now (sorry the commit history looks so messy). I had thought that `76-not-case-sensitive` was built on top of `73-table-backup` so that the backup table functions + the case sensitive check happened in the same branch, but now i realize they're not. i will retry my `pytests`

hmm i'm still seeing non-test changes in the diff...

**Comment by cindyatnycdot** [comment]
> > It was from `73-table-backup`. I've fixed the rebase now (sorry the commit history looks so messy). I had thought that `76-not-case-sensitive` was built on top of `73-table-backup` so that the backup table functions + the case sensitive check happened in the same branch, but now i realize they're not. i will retry my `pytests`
> 
> hmm i'm still seeing non-test changes in the diff...

Yes I can't seem to get rid of the previous commits from this PR. To solve this, I will just make a new branch and remove this one.

**Pull request closed without merging**
